# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20170205_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='description',
            new_name='name',
        ),
    ]
