# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20170205_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_type',
            field=models.CharField(choices=[('tlp', 'Tulip TLP'), ('ind', 'Industry Standard')], default='tlp', max_length=3, verbose_name='Network Type'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Network Name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.FileField(upload_to='networks/', verbose_name='Network File'),
        ),
    ]
