# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20170228_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network',
            new_name='network_file',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='name',
            new_name='network_name',
        ),
    ]
