# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_auto_20170228_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Network Name'),
        ),
    ]
